#!/usr/bin/env bun
// Render the Homebrew formula for a release from the .sha256 files in dist/.
//
//   bun scripts/formula.ts --version 2.1.0 [--repo owner/name] [--dist dist] > chatty.rb

import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
const opt = (name: string, fallback?: string) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};

const version = opt("version")?.replace(/^v/, "");
const repo = opt("repo", process.env.GITHUB_REPOSITORY ?? "HarshDodiya1/ChaTTY")!;
const dist = path.resolve(opt("dist", "dist")!);
if (!version) {
  console.error("usage: formula.ts --version <x.y.z> [--repo owner/name] [--dist dir]");
  process.exit(2);
}

const sha = (target: string): string => {
  const file = path.join(dist, `chatty-${version}-${target}.tar.gz.sha256`);
  if (!fs.existsSync(file)) {
    console.error(`missing ${file}`);
    process.exit(1);
  }
  return fs.readFileSync(file, "utf8").split(/\s+/)[0]!;
};

const url = (target: string) =>
  `https://github.com/${repo}/releases/download/v${version}/chatty-${version}-${target}.tar.gz`;

const block = (target: string) => `      url "${url(target)}"
      sha256 "${sha(target)}"`;

process.stdout.write(`# typed: false
# frozen_string_literal: true

# This file is generated by scripts/formula.ts in ${repo} — do not edit by hand.
class Chatty < Formula
  desc "Peer-to-peer LAN terminal chat with end-to-end encryption"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${block("darwin-arm64")}
    end
    on_intel do
${block("darwin-x64")}
    end
  end

  on_linux do
    on_arm do
${block("linux-arm64")}
    end
    on_intel do
${block("linux-x64")}
    end
  end

  def install
    bin.install "chatty"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chatty --version")
    assert_match "peer-to-peer", shell_output("#{bin}/chatty --help")
  end
end
`);
